# Generated by Django 6.0 on 2026-01-10 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '词汇分类',
                'verbose_name_plural': '词汇分类',
            },
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='单词')),
                ('translation', models.CharField(max_length=200, verbose_name='中文翻译')),
                ('meaning', models.TextField(verbose_name='详细含义')),
                ('level', models.CharField(choices=[('CET-4', 'CET-4'), ('CET-6', 'CET-6'), ('Academic', '学术词汇'), ('Business', '商务词汇'), ('Technology', '科技词汇'), ('Daily', '日常词汇'), ('Advanced', '高级词汇'), ('TOEFL', '托福词汇'), ('IELTS', '雅思词汇'), ('Professional', '专业词汇'), ('Science', '科学词汇'), ('Medical', '医学词汇'), ('Legal', '法律词汇'), ('Engineering', '工程词汇'), ('Finance', '金融词汇'), ('Education', '教育词汇')], db_index=True, max_length=20, verbose_name='词汇级别')),
                ('pronunciation', models.CharField(blank=True, max_length=100, verbose_name='音标')),
                ('example_sentence', models.TextField(blank=True, verbose_name='例句')),
                ('example_translation', models.TextField(blank=True, verbose_name='例句翻译')),
                ('frequency', models.IntegerField(default=0, verbose_name='使用频率')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '词汇',
                'verbose_name_plural': '词汇库',
                'ordering': ['level', 'word'],
                'indexes': [models.Index(fields=['word'], name='word_vocabu_word_fffe54_idx'), models.Index(fields=['level'], name='word_vocabu_level_1e3f02_idx'), models.Index(fields=['word', 'level'], name='word_vocabu_word_cdfad3_idx')],
            },
        ),
        migrations.CreateModel(
            name='VocabularyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word.vocabulary', verbose_name='词汇')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word.wordcategory', verbose_name='分类')),
            ],
            options={
                'verbose_name': '词汇分类关联',
                'verbose_name_plural': '词汇分类关联',
                'unique_together': {('vocabulary', 'category')},
            },
        ),
    ]
